version: 0.2
env:
  #secrets-manager: 
  #  DOCKERHUB_USER : DEV/ECS/DOCKERHUB:user
  #  DOCKERHUB_TOKEN: DEV/ECS/DOCKERHUB:token
  parameter-store:
    DOCKERHUB_USER: /dockerhub/user
    DOCKERHUB_TOKEN: /dockerhub/token
  variables:
    ECR_REPO_NAME: js/my-angular-app

phases:
  pre_build:
    commands:
      # Docker Hub login
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
      
      # ECR Login
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}
      #- ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}  
      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:${IMAGE_TAG}"
  build: 
    commands:
      - docker build -t ${ECR_REPO_NAME}:latest .

  post_build:
    commands:
      - docker tag ${ECR_REPO_NAME}:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}
      - printf '[{"name":"angular-app","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

